### ISSUE TITLE
Upgrade to Drupal 9

### ISSUE THREAD

**Issue by willguv** [localgovdrupal/localgov#181]
Note from Adnan

IMHO upgrading to Drupal 9 should be the first thing the beta supplier should do.  It's not a monumental task. The upgraded Drupal core should just work.  It's some of the contrib modules that will fail in which case we will have to source patches for them from their Drupal.org issue queue and add to the relevant config files in LGD.

When working on LGD code last year, I was routinely using stock Drupal 9 instead of LGD.  This was to ensure that the code works both inside and outside of LGD.  I had a few issues, but they were easy to solve.  Based on that experience, I doubt it will take more than three days of development time to switch LGD from Drupal 8 to Drupal 9.

**Comment by andybroomfield** [comment]
See also #59

There is a branch for this, but not had much luck getting it working. @Adnan-cds can you share how you are getting Drupal 9 working with localgov, as it would be good to test this.

I tried altering the (outdated) branch @finnlewis set up for Drupal 9. I had to remove localgov_events as date recur is not compatible. I also get the following error on install
````
Invalid data type in config geolocation_google_maps.schema, found in file modules/contrib/geolocation/modules/geolocation_google_maps/config/schema/geolocation_google_maps.schema.yml: Duplicate key "height" detected at line 132 (near "  label: 'Height  
   value'"). 
````

**Comment by danchamp** [comment]
> I also get the following error on install
> 
> ```
> Invalid data type in config geolocation_google_maps.schema, found in file modules/contrib/geolocation/modules/geolocation_google_maps/config/schema/geolocation_google_maps.schema.yml: Duplicate key "height" detected at line 132 (near "  label: 'Height  
>    value'"). 
> ```

@andybroomfield That's fixed in a module patch, covered in [this pending PR](https://github.com/localgovdrupal/localgov_paragraphs/pull/17)

**Comment by andybroomfield** [comment]
@danchamp I don't think that is correct as that patch is already being applied in locagov_paragraphs and it still fails.

**Comment by danchamp** [comment]
@andybroomfield It's [patch 5](https://www.drupal.org/files/issues/2021-01-27/geolocation-google-maps-schema-update-3138668-5.patch) from that module issue that needs to be applied, I think it's patch 2 that's currently applied in localgov_paragraphs and introduces the duplicate height key.

**Comment by andybroomfield** [comment]
@danchamp ok, thanks for the info

**Comment by Adnan-cds** [comment]
> can you share how you are getting Drupal 9 working with localgov, as it would be good to test this.

Hi Andy,
I was using Drupal 9 while working on individual localgov modules (i.g. localgov_directories, localgov_menu_link_group, etc.) last year to ensure that these modules work independently of localgov.  In almost all cases, I had to get a patch or two from drupal.org issue queues for various contrib modules.  So this Drupal 8 to Drupal 9 upgrade is mostly an exercise in sourcing the right patch from the right place.  We may even have to create a few new patches.  Finn and Steve have been doing this from the very  start of LocalGov, so hopefully this won't be too complicated.

**Comment by finnlewis** [comment]
Hey all,
Yes, there are a few patches needed for some contrib modules, but the number should be decreasing and in some cases we might just need to change the module version. 
I'll jump back onto this and see if I can help. 
We've been doing a bunch of D9 upgrade recently s have a few experiences to draw upon. 
Let's try to get that branch back up and running.: https://github.com/localgovdrupal/localgov/tree/feature/59-drupal-9 
date_recur might be a pain though... or not actually  https://www.drupal.org/project/date_recur/releases/3.0.0

**Comment by finnlewis** [comment]
@andybroomfield I see you've started https://github.com/localgovdrupal/localgov/commits/feature/59a-drupal-9 too. 

Shall we collaborate on that or would you rather test in parallel ?

**Comment by andybroomfield** [comment]
@finnlewis I was just testing to see if I could get a Drupal 9 branch working, as I saw your version but it still had a drupal 8.9 as the requirement.

I think what we need to do is coordinate drupal 9 support across all modules that have dependencies that need to be patched and do a drupal 9 branch of the project that brings in the correct branches.

**Comment by finnlewis** [comment]
@andybroomfield I have something working....

```
composer create-project --stability dev localgovdrupal/localgov-project:dev-feature/38-drupal-9 TESTBED
cd TESTBED/
lando  start
lando drush si localgov
lando drush status
 Drupal version   : 9.1.5                             
 Site URI         : https://localgov.lndo.site        
 DB driver        : mysql                             
 DB hostname      : database                          
 DB port          : 3306                              
 DB username      : database                          
 DB name          : database                          
 Database         : Connected                         
 Drupal bootstrap : Successful                        
 Default theme    : localgov_theme                    
 Admin theme      : claro                             
 PHP binary       : /usr/local/bin/php                
 PHP config       :                                   
 PHP OS           : Linux                             
 Drush script     : /app/vendor/drush/drush/drush     
 Drush version    : 10.3.6                            
 Drush temp       : /tmp                              
 Drush configs    : /app/vendor/drush/drush/drush.yml 
 Install profile  : localgov                          
 Drupal root      : /app/web                          
 Site path        : sites/default                     
 Files, Public    : sites/default/files               
 Files, Temp      : /tmp                              
```

I've created branches where I thought needed, hanging each off an issue. The main challenge I had was getting the composer dependency chain to work with a different branch of paragraphs. 

There was probably an easier way, but it is nice to know it installs at least. 

Next up - coding standards and tests across the projects.

**Comment by finnlewis** [comment]
See the following branches : 
https://github.com/localgovdrupal/localgov_project/tree/feature/38-drupal-9
https://github.com/localgovdrupal/localgov/tree/feature/59-drupal-9
https://github.com/localgovdrupal/localgov_services/tree/feature/97-drupal-9
https://github.com/localgovdrupal/localgov_subsites/tree/feature/20-drupal-9
https://github.com/localgovdrupal/localgov_events/tree/feature/24-drupal-9

**Comment by finnlewis** [comment]
Issues for failing tests, only 6 as far as I can see:  
https://github.com/localgovdrupal/localgov/issues/182
https://github.com/localgovdrupal/localgov_services/issues/97
https://github.com/localgovdrupal/localgov_alert_banner/issues/113

**Comment by andybroomfield** [comment]
<img width="1182" alt="Screenshot 2021-03-17 at 11 19 51 pm" src="https://user-images.githubusercontent.com/1467480/111551097-59a86c00-8777-11eb-89a8-9ab6fb26b826.png">

**Comment by stephen-cox** [comment]
Just giving branch feature/38-drupal-9 a spin.

Having installed a Drupal 8 site with the demo content module enabled, the upgrade went fine, but accessing service landing pages  throws a `Drupal\Core\Entity\Query\QueryException: 'field_service_status_on_landing' not found in Drupal\Core\Entity\Query\Sql\Tables->ensureEntityTable() (line 368 of core/lib/Drupal/Core/Entity/Query/Sql/Tables.php). ` error.

Running a Drush site install files with `Configuration objects provided by <em class="placeholder">localgov_services_page</em> have unmet dependencies: <em class="placeholder">field.field.node.localgov_services_page.field_page_components (field.storage.node.field_page_components)</em>`

There are now also a number of test failures related to this second error.

**Comment by stephen-cox** [comment]
Issues I was seeing where due to Drupal 9 branch of the Services module diverging from master. We'll need to keep an eye on this as the Drupal 9 work proceeds.

I've been looking at fixing some PHPUnit tests, but have also seen that there are coding standards changes between Drupal 8 and 9, and also deprecated code changes that will need to be fixed if our tests are to pass.

**Comment by stephen-cox** [comment]
Done - sprint 3
